global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: soundverse
    scheme: https
    static_configs:
      - targets:
          - soundverse-assignment-nz64.onrender.com
    metrics_path: /metrics
